//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_Uzbekistan {
        displayName = "Uzbek Armed Forces";
        side = 0;
        flag = "ca\Ca_E\data\flag_tkg_co.paa";
        icon = "ca\Ca_E\data\flag_tkg_co.paa";
        priority = 1;
    };
};