//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_Uzbekistan {
            name = "Uzbek Armed Forces";

            class Infantry {
                name = "Infantry";

                class o_uzbek_infantry_fire_team_lmg {
                    name = "Fire Team (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "ua_ka_Autorifleman";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_fire_team_gpmg {
                    name = "Fire Team (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74MR_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_fire_team_mk {
                    name = "Fire Team (MK)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                };

                class o_uzbek_infantry_fire_team_at {
                    name = "Fire Team (AT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKM_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_01";
                    };
                };

                class o_uzbek_infantry_fire_team_engineer {
                    name = "Fire Team (Engineer)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Engineer_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_Alt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_01";
                    };
                };

                class o_uzbek_infantry_fire_team_gl {
                    name = "Fire Team (GL)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_01";
                    };
                };

                class o_uzbek_infantry_fire_team_lat {
                    name = "Fire Team (LAT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_Alt_01";
                    };
                };

                class o_uzbek_infantry_fire_team_rifle {
                    name = "Fire Team (Rifle)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74MR_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_01";
                    };
                };

                class o_uzbek_infantry_gpmg_team {
                    name = "GPMG Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKM_01";
                    };
                };

                class o_uzbek_infantry_mat_team {
                    name = "MAT Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                };

                class o_uzbek_infantry_manpad_team {
                    name = "MANPAD Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_antiair.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_01";
                    };
                };

                class o_uzbek_infantry_squad_lmg {
                    name = "Squad (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_squad_lmg_rpg {
                    name = "Squad (LMG/RPG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_Alt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_01";
                    };
                };

                class o_uzbek_infantry_squad_gpmg {
                    name = "Squad (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74MR_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                };

                class o_uzbek_infantry_squad_gpmg_rpg {
                    name = "Squad (GPMG/RPG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_Alt_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKM_01";
                    };
                };

                class o_uzbek_infantry_squad_weapons {
                    name = "Squad (Weapons)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_01";
                    };
                };

                class o_uzbek_infantry_sentry {
                    name = "Sentry";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_01";
                    };
                };

                class o_uzbek_infantry_sentry_lmg {
                    name = "Sentry (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_sentry_gpmg {
                    name = "Sentry (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                };

                class o_uzbek_infantry_sentry_mk {
                    name = "Sentry (MK)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_01";
                    };
                };

                class o_uzbek_infantry_sentry_mk_night {
                    name = "Sentry (MK-Night)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_Night_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74M_Night_01";
                    };
                };

                class o_uzbek_infantry_sentry_at {
                    name = "Sentry (AT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_sentry_manpad {
                    name = "Sentry (MANPAD)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_antiair.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_01";
                    };
                };

                class o_uzbek_infantry_sentry_medic {
                    name = "Sentry (Medic)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_74_Alt_01";
                    };
                };

                class o_uzbek_infantry_sentry_gl {
                    name = "Sentry (GL)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                };

                class o_uzbek_infantry_sentry_lat {
                    name = "Sentry (LAT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                };

                class o_uzbek_infantry_sentry_light {
                    name = "Sentry (Light)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_M38_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class o_uzbek_specops_recon_team_lmg {
                    name = "Recon Team (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74MR_01";
                    };
                };

                class o_uzbek_specops_recon_team_gpmg {
                    name = "Recon Team (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                };

                class o_uzbek_specops_recon_team_mk {
                    name = "Recon Team (MK)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74MR_01";
                    };
                };

                class o_uzbek_specops_recon_team_mk_night {
                    name = "Recon Team (MK-Night)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_M4_01";
                    };
                };

                class o_uzbek_specops_recon_team_at {
                    name = "Recon Team (AT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                };

                class o_uzbek_specops_recon_team_sapper {
                    name = "Recon Team (Sapper)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_103_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Sapper_01";
                    };
                };

                class o_uzbek_specops_gpmg_team {
                    name = "GPMG Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                };

                class o_uzbek_specops_manpad_team {
                    name = "MANPAD Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74MR_01";
                    };
                };

                class o_uzbek_specops_recon_squad_lmg {
                    name = "Recon Squad (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Medic_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Sapper_01";
                    };
                };

                class o_uzbek_specops_recon_squad_lmg_rpg {
                    name = "Recon Squad (LMG/RPG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RShG_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Medic_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_02";
                    };
                };

                class o_uzbek_specops_recon_squad_gpmg {
                    name = "Recon Squad (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Medic_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Sapper_01";
                    };
                };

                class o_uzbek_specops_recon_squad_gpmg_rpg {
                    name = "Recon Squad (GPMG/RPG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RShG_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Medic_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_02";
                    };
                };

                class o_uzbek_specops_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_M4_01";
                    };
                };

                class o_uzbek_specops_patrol_lmg {
                    name = "Patrol (LMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                };

                class o_uzbek_specops_patrol_gpmg {
                    name = "Patrol (GPMG)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74MR_01";
                    };
                };

                class o_uzbek_specops_patrol_mk {
                    name = "Patrol (MK)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                };

                class o_uzbek_specops_patrol_mk_night {
                    name = "Patrol (MK-Night)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_Night_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_AK_74M_01";
                    };
                };

                class o_uzbek_specops_patrol_lat {
                    name = "Patrol (LAT)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class o_uzbek_motorized_motorized_infantry_squad_btr_80a {
                    name = "Motorized Infantry Squad (BTR-80A)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BTR_80A_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                };

                class o_uzbek_motorized_motorized_infantry_squad_btr_80 {
                    name = "Motorized Infantry Squad (BTR-80)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BTR_80_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                };

                class o_uzbek_motorized_motorized_infantry_squad_btr_70 {
                    name = "Motorized Infantry Squad (BTR-70)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                };

                class o_uzbek_motorized_motorized_infantry_squad_btr_60pb {
                    name = "Motorized Infantry Squad (BTR-60PB)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                };

                class o_uzbek_motorized_motorized_sf_squad_maxxpro_m2 {
                    name = "Motorized SF Squad (MAXXPRO M2)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_MAXXPRO_M2_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RShG_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Scout_M4_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Marksman_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Sapper_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Medic_02";
                    };
                };

                class o_uzbek_motorized_motorized_sf_squad_maxxpro_rcws_m2 {
                    name = "Motorized SF Squad (MAXXPRO RCWS/M2)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_MAXXPRO_CROWS_M2_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_air_9K38_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Sapper_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Scout_GP_25_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Scout_RPG_26_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class o_uzbek_support_repair_team {
                    name = "Repair Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Ural_4320_Repair_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Engineer_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Engineer_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class o_uzbek_mechanized_mechanized_infantry_squad_bmp {
                    name = "Mechanized Infantry Squad (BMP-2)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BMP_2obr_1986g_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_M38_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AK_105_Alt_01";
                    };
                };

                class o_uzbek_mechanized_mechanized_infantry_squad_bmp_1p {
                    name = "Mechanized Infantry Squad (BMP-1P)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BMP_1P_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_26_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_RPG_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Anti_tank_Assistant_01";
                    };
                };

                class o_uzbek_mechanized_mechanized_infantry_squads_bmp {
                    name = "Mechanized Infantry Squad (BMP-1)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BMP_1_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_AKS_74_Alt_01";
                    };
                };

                class o_uzbek_mechanized_mechanized_infantry_squad_bmd {
                    name = "Mechanized Infantry Squad (BMD-1)";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BMD_1_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_RPG_18_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Machinegunner_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_GP_25_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Fighter_M38_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class o_uzbek_armored_t80_platoon {
                    name = "T-80 Platoon";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                    class Unit1 {
                        position[] = {7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                    class Unit2 {
                        position[] = {-7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                    class Unit3 {
                        position[] = {14,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                };

                class o_uzbek_armored_t80_section {
                    name = "T-80 Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                    class Unit1 {
                        position[] = {7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T80BV_01";
                    };
                };

                class o_uzbek_armored_t72_platoon {
                    name = "T-72 Platoon";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1985g_01";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1984g_01";
                    };
                    class Unit2 {
                        position[] = {-10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1984g_01";
                    };
                    class Unit3 {
                        position[] = {20,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1985g_01";
                    };
                };

                class o_uzbek_armored_t72_section {
                    name = "T-72 Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1985g_01";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_T72B_obr_1984g_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class o_uzbek_artillery_d30a_section {
                    name = "D-30A Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_2A18M_D30A_01";
                    };
                    class Unit1 {
                        position[] = {9,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_2A18M_D30A_01";
                    };
                };

                class o_uzbek_artillery_podnos_section {
                    name = "Podnos Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_2B14_1Podnos_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_2B14_1Podnos_01";
                    };
                };

                class o_uzbek_artillery_bm_21_section {
                    name = "BM-21 Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_BM_21_01";
                    };
                    class Unit1 {
                        position[] = {5,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_BM_21_01";
                    };
                };

                class o_uzbek_artillery_2s3m_section {
                    name = "2S3M Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_2S3M1_01";
                    };
                    class Unit1 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_2S3M1_01";
                    };
                };

                class o_uzbek_artillery_2s1_section {
                    name = "2S1 Section";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_2S1_01";
                    };
                    class Unit1 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_2S1_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class o_uzbek_air_hind_hunting_team {
                    name = "Hind Hunting Team";
                    side = 0;
                    faction = "O_Uzbekistan";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_uzbek_Mi_24VM_01";
                    };
                    class Unit1 {
                        position[] = {23,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_uzbek_Mi_24VM_01";
                    };
                };

            };


        };

    };
};