name = "Spagistan Armed Forces Equipment";
picture = "spagistan_logo_ca.paa";
actionName = "GitHub";
action = "https://units.arma3.com/unit/spagistan";
description = "Spag - Version 1.6.4";
logo = "spagistan_logo_ca.paa";  //TODO: replace with 2048x1024
logoOver = "spagistan_logo_ca.paa";
tooltip = "SPAG";
tooltipOwned = "SPAG Owned";
overview = "Spagistan Armed Forces Equipment";
author = "Spagistan Team";
overviewPicture = "spagistan_logo_ca.paa";
