			clearWeaponCargoGlobal _vehicle;  
            clearMagazineCargoGlobal _vehicle;  
            clearItemCargoGlobal _vehicle;  
            clearBackpackCargoGlobal _vehicle;  
            _vehicle addWeaponCargoGlobal ["rhs_weap_ak74m", 2];  
            _vehicle addWeaponCargoGlobal ["rhs_weap_rpg75", 2];  
            _vehicle addWeaponCargoGlobal ["rhs_weap_igla", 1]; 
            _vehicle addWeaponCargoGlobal ["rhs_weap_rpg7", 1]; 
            _vehicle addMagazineCargoGlobal ["rhs_mag_9k38_rocket", 4]; 
            _vehicle addMagazineCargoGlobal ["rhs_rpg7_PG7VS_mag", 6]; 
            _vehicle addMagazineCargoGlobal ["rhs_rpg7_type69_airburst_mag", 4]; 
            _vehicle addMagazineCargoGlobal ["rhs_rpg7_TBG7V_mag", 2]; 
            _vehicle addMagazineCargoGlobal ["grcb_30Rnd_545x39_7N24_AK", 20];  
            _vehicle addMagazineCargoGlobal ["grcb_60Rnd_545x39_7N24", 10];  
            _vehicle addMagazineCargoGlobal ["rhs_VOG25", 20];  
            _vehicle addMagazineCargoGlobal ["rhs_GRD40_white", 10];  
            _vehicle addMagazineCargoGlobal ["rhssaf_mag_br_m75", 10];  
            _vehicle addMagazineCargoGlobal ["rhssaf_mag_brd_m83_white", 10]; 
            _vehicle addItemCargoGlobal ["ACE_Clacker", 1];
            _vehicle addItemCargoGlobal ["DemoCharge_Remote_Mag", 1];
            _vehicle addItemCargoGlobal ["rhs_acc_pgo7v3", 2];  
            _vehicle addItemCargoGlobal ["ACE_wirecutter", 1]; 
            _vehicle addItemCargoGlobal ["ACE_elasticBandage", 20];  
            _vehicle addItemCargoGlobal ["ACE_packingBandage", 20];  
            _vehicle addItemCargoGlobal ["ACE_morphine", 5];  
            _vehicle addItemCargoGlobal ["ACE_epinephrine", 5];  
            _vehicle addItemCargoGlobal ["ACE_tourniquet", 5];  
            _vehicle addItemCargoGlobal ["ACE_splint", 5];  
            _vehicle addItemCargoGlobal ["ACE_EarPlugs", 3];  
            _vehicle addItemCargoGlobal ["ACE_suture", 20];  
            _vehicle addItemCargoGlobal ["ACE_salineIV_500", 5];  
            _vehicle addMagazineCargoGlobal ["cigs_morley_cigpack", 1];
