
class GenericNames
{
    class SpagistanMen
    {
        class FirstNames
        {
            sulton="Sulton";
            zahid="Zahid";
            rahmat="Rahmat";
            otabek="Otabek";
            mustariy="Mushtariy";
            ziyod="Ziyod";
            alim="Alim";
            nurullo="Nurullo";
            husan="Husan";
            mansur="Mansur";
            behzod="Behzod";
            ilhom="Ilhom";
            elyor="Elyor";
            anvar="Anvar";
            husniddin="Husniddin";
            zafar="Zafar";
            akmal="Akmal";
            abidin="Abidin";
            eldor="Eldor";
            khakim="Khakim";
            zayd="Zayd";
            husayn="Husayn";
            nusrat="Nusrat";
            kamol="Kamol";
            zokhid="Zokhid";
            sigaretta="Sigaretta";
            saddam="Saddam";
            billy="Billy";
            van="Van";
            john="John";
        };
        class LastNames
        {
            xamidov="Xamidov";
            yusupov="Yusupov";
            yakubov="Yakubov";
            gulamov="Gulamov";
            latipov="Latipov";
            beknazarov="Beknazarov";
            mukhammadiev="Mukhammadiev";
            kudratov="Kudratov";
            polkovnik="Polkovnik";
            mansurov="Mansurov";
            ulugbek="Ulugbek";
            ahmedov="Ahmedov";
            yakub="Yaqub";
            rustamov="Rustamov";
            davlatov="Davlatov";
            gairatov="Gairatov";
            kamolov="Kamolov";
            ganiev="Ganiev";
            saidov="Saidov";
            vohidov="Vohidov";
            ibragimoc="Ibragimov";
            mustafoev="Mustafoev";
            islomov="Islomov";
            toshmatov="Toshmatov";
            herrington="Herrington";
            darkholme="Darkholme";
            spagistani="Spagistani";
        };
    };
};

