[lints.sqf]
static_typename = false
command_case = false
if_assign = false
find_in_str = false
select_parse_number = false
format_args = false
banned_commands = false
if_not_else = false
unused = false
invalid_args = false
undefined = false
shadowed = false
not_private = false
var_all_caps = false
in_vehicle_check = false
extra_not = false
bool_static_comparison = false
invalid_comparisons = false
this_call = false
reasign_reserved_variable = false
marker_update_spam = false
count_array_comp = false
short_circuit_bool_var = false
select_count = false
banned_macros = false
config_of = false
missing_file = false
reimplementing_command = false
count_skippable = false
