//infosign0 addAction ["Read sign", {cutText ["TEXT HERE", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
/*
infosign1 addAction ["Read sign", {cutText ["These signs are part of the Spagistan Cultural Preservation Project. You will find them at culturally significant places all around our country. We encourage you to visit them all and carry on the history of our people.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign2 addAction ["Read sign", {cutText ["Saddam Hussein (peace be upon him) is considered a dear friend to the people of Spagistan. Please show him respect.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign3 addAction ["Read sign", {cutText ["This is the Garsmar Cadets Academy, a military academy for the armed forces. It is a very special school for those who failed to be placed in any other vocation. Please do not make any sudden sounds or movements when near the cadets; they get startled easily.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign4 addAction ["Read sign", {cutText ["This is the residence of Colonel Spag Hetta, our supreme leader. You may find Him here when He is not leading His armed forces on an expeditionary campaign.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign5 addAction ["Read sign", {cutText ["This is the Chak Chak Grand Bazaar, Spagistan's symbol of resilience. It lies in disrepair due to a terrorist attack conducted by Russian-backed insurgents in October of 2024. This attacked galvanized the Spagistan Armed Forces to initiate Operation Sunrise in neighboring Sa'hatra.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign6 addAction ["Read sign", {cutText ["This is the headquarters of the Feruz Abad Pipeworkers Union. They have been 'laying' that pipe' since 2017.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign7 addAction ["Read sign", {cutText ["This is the site of the Nuclear Incident. A nuclear Scud missile was accidentally launched at ISIS forces that were invading our country.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign8 addAction ["Read sign", {cutText ["The 'pontoon bridge incident' is currently being researched. Come back soon!", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign9 addAction ["Read sign", {cutText ["This is a restricted military area. Please leave the premises immediately.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
infosign10 addAction ["Read sign", {cutText ["Sergeant Major Billy Herrington is a cultural icon and national treasure to the Spagistani people. His films have not only entertained us, but have been insightful teaching aids for hand-to-hand combat. Today, he holds the important position of shaping Garmsar cadets into proper soldiers.", "PLAIN", 2]}, [], 6, false, true, "", "_target distance _this < 2"];
*/