[default]
workshop = [
    "450814997", # CBA_A3
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
    "894678801", # TFAR Workshop ID
]