[default]
workshop = [

    "450814997",  # CBA_A3 Workshop ID
    "463939057",  # ACE3 Workshop ID
    "843425103",  # RHS AFRF Workshop ID
    "843577117",  # RHS USAF Workshop ID
    "843593391",  # RHS GREF Workshop ID
    "843632231",  # RHS SAF  Workshop ID
    "894678801",  # TFAR Workshop ID
    "583496184",  # CUP Terrains - Core Workshop ID
    "583544987",  # CUP Terrains - Maps
    "2890312862", # Uncon Actions Workshop ID
    "3125837686", # Bulat UAV Workshop ID
    "3045129955", # FPV Drone Crocus Workshop ID
    "1779063631", # Zeus Enhanced Workshop ID
    "2447965207", # Crows Zeus Addition Workshop ID
    "2826534435", # Enhanced MI-24
    "3435291098", # Gym Bench
    "3058335345", # TBD Mortars
    "3356373534", # TBD D20
    "3183189354", # TBD 2B9
    "3251627825", # TBD MT12
    "3382728502", # TBD Type 63
    "3375788189", # Immersive Cigs Rewrite
    "2890312862", # Unconventional Actors
    "1885205711", # RHS Mixed Mags
    "2522638637", # ACE3 Arsenal Extended - Core
]

[arty]
extends = "default"
mission = "operationironveilwinter.chernarus_winter"
