name = "Spagistan Armed Forces Equipment"
author = "Cédric Paradis"
prefix = "spag"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
build = 0

[hemtt.launch.default]
workshop=[
    '450814997'

]
mission= "test.VR"