name = "Spagistan Armed Forces Equipment"
author = "Cédric Paradis"
prefix = "spag"
mainprefix = "z"

[version]
path = "addons/spag_main/script_version.hpp"
git_hash = 0


[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README*.md",  # Translated READMEs get moved to root in a hook (virtual file system)
    "AUTHORS.txt",
    "LICENSE",
    "spagistan_logo_ca.paa",
    "meta.cpp",
]
exclude = [
    "base_textures/**"
]