//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_Spagistan_Garmsar {
            name = "Spagistan Garmsar Cadets";

            class Infantry {
                name = "Infantry";

                class i_spagistan_garmsar_infantry_garmsar_cadet_squad {
                    name = "Garmsar Cadet Squad";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Sergeant_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                };

                class i_spagistan_garmsar_infantry_garmsar_cadet_team {
                    name = "Garmsar Cadet Team";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Sergeant_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                };

                class i_spagistan_garmsar_infantry_garmsar_cadet_patrol {
                    name = "Garmsar Cadet Patrol";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Sergeant_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_spagistan_garmsar_motorized_garmsar_boys_truck_team {
                    name = "Garmsar Boys Truck Team";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Boys_Truck_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Sergeant_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                };

                class i_spagistan_garmsar_motorized_garmsar_boys_truck_squad {
                    name = "Garmsar Boys Truck Squad";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Boys_Truck_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Sergeant_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Cadet_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

                class i_spagistan_garmsar_artillery_boys_mortar_section {
                    name = "Boys Mortar Section";
                    side = 2;
                    faction = "I_Spagistan_Garmsar";
                    icon = "\A3\ui_f\data\map\markers\nato\n_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Boys_Mortar_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Spagistan_Garmsar_Garmsar_Boys_Mortar_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};