class CfgPatches {
    class I_Spagistan_Garmsar {
        units[] = {
            "I_Spagistan_Garmsar_Garmsar_Cadet_01",
            "I_Spagistan_Garmsar_Garmsar_Driving_Boy_01",
            "I_Spagistan_Garmsar_Garmsar_Gunner_Boy_01",
            "I_Spagistan_Garmsar_Garmsar_Fuel_Truck_02",
            "I_Spagistan_Garmsar_Garmsar_Ammo_Truck_01",
            "I_Spagistan_Garmsar_Garmsar_Boys_Truck_02",
            "I_Spagistan_Garmsar_Garmsar_Repair_Truck_01",
            "I_Spagistan_Garmsar_Garmsar_Sergeant_01",
            "I_Spagistan_Garmsar_Garmsar_Boys_Mortar_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "spag_Factions",
            "A3_Characters_F",
            "rhs_c_troops",
            "rhs_cti_insurgents",
            "rhsgref_c_troops",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "immersion_pops",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "A3_Data_F",
            "ibr_yulakia_c",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "ace_thermals",
            "zen_attributes",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh",
            "ua_chvk",
            "rhs_c_a2port_car",
            "ace_compat_rhs_afrf3",
            "rhs_c_vehiclesounds",
            "ace_compat_rhs_afrf3_repair",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "ace_repair",
            "rhssaf_c_vehicles",
            "ace_cargo",
            "rhsgref_c_vehicles_ret",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "ace_interaction",
            "ace_tagging",
            "ace_vehicles",
            "A3_Armor_F_Beta",
            "rhs_c_heavyweapons",
            "ace_compat_rhs_afrf3_csw",
            "A3_Static_F",
            "A3_Static_F_AA_01",
            "A3_Static_F_AT_01",
            "rhsusf_c_statics",
            "ace_dragging"
        };
        author = "Canadian";
        authors[] = {"Canadian"};
    };
};
