//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_SPAG_Militia {
        displayName = "Spagistani Militia";
        side = 2;
        flag = "\z\spag\addons\common\gui\Spag_Flag_ca.paa";
        icon = "\z\spag\addons\common\gui\Spag_Flag_Square_ca.paa";
        priority = 7;
    };

    class O_SPAG_Militia_OPFOR {
        displayName = "Spagistani Militia";
        side = 0;
        flag = "\z\spag\addons\common\gui\Spag_Flag_ca.paa";
        icon = "\z\spag\addons\common\gui\Spag_Flag_Square_ca.paa";
        priority = 7;
    };

        class C_SPAG_Civilian {
        displayName = "Spagistani Civilians";
        side = 3;
        flag = "\z\spag\addons\common\gui\Spag_Flag_ca.paa";
        icon = "\z\spag\addons\common\gui\Spag_Flag_Square_ca.paa";
        priority = 7;
    };
};
