//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CBA_Extended_EventHandlers_base;
class EventHandlers;
class I_G_Soldier_base_F;

class CfgVehicles {

    class I_Spagistan_Militiaman_Base : I_G_Soldier_base_F {
    author = "A. Dan";
        scope = 0;
        scopeCurator = 0;
        side = 2;
        genericNames = "SpagistanMen";
        faction = "I_SPAG_Militia";
        editorCategory = "Spagistani_Militia_Category";
        identityTypes[] = {"Head_TK","LanguagePER_F"};
        Items[] = { "cigs_matches", "ACE_tourniquet", "uzbek_Wallet" };
		RespawnItems[] = { "cigs_matches", "ACE_tourniquet" };
        headgearList[] =
		{
			"H_FakeHeadgear", 0.7,
			"S_Pakol", 0.5,
            "S_Turban", 0.5,
            "rhs_pilotka", 0.5,
            "rhs_fieldcap_m88_back", 0.5,
            "rhs_fieldcap_m88_", 0.2,
            "S_beret_green_NONE", 0.2,
            "H_Cap_red", 0.2
		};

		class EventHandlers : EventHandlers
		{
			init = "if (local (_this select 0)) then { [(_this select 0), [], []] call BIS_fnc_unitHeadgear; };";
        };
    };



    class I_Spagistan_Militiaman_Izh18 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Shotgun)";
        uniformClass = "U_I_C_Soldier_Bandit_4_F";
        weapons[] = {"rhs_weap_Izh18"};
        respawnWeapons[] = {"rhs_weap_Izh18"};
        magazines[] = { ITEM_8("rhsgref_1Rnd_Slug"), ITEM_11("rhsgref_1Rnd_00Buck") };
        respawnMagazines[] = { ITEM_8("rhsgref_1Rnd_Slug"), ITEM_11("rhsgref_1Rnd_00Buck") };
        linkedItems[] = {"rhs_suspender_AK","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"rhs_suspender_AK","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
    };

    class I_Spagistan_Militiaman_PM_63 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (AK Rifle)";
        uniformClass = "U_I_C_Soldier_Bandit_1_F";
        linkedItems[] = {"rhs_gear_OFF","S_beret_green_NONE","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_gear_OFF","S_beret_green_NONE","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pm63"};
        respawnWeapons[] = {"rhs_weap_pm63"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pm63","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"U_I_C_Soldier_Bandit_1_F",{}},{"rhs_gear_OFF",{{"rhs_30Rnd_762x39mm",2,30}}},{},"S_beret_green_NONE","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};

    };

    class I_Spagistan_Militiaman_M84 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (GPMG)";
        uniformClass = "U_C_Poloshirt_stripped";
        linkedItems[] = {"rhs_chicom_khk","S_Pakol","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_chicom_khk","S_Pakol","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m84"};
        respawnWeapons[] = {"rhs_weap_m84"};

        magazines[] = {"rhs_100Rnd_762x54mmR_7N13","rhs_100Rnd_762x54mmR_7N13"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR_7N13","rhs_100Rnd_762x54mmR_7N13"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m84","","","",{"rhs_100Rnd_762x54mmR_7N13",100},{},""},{},{},{"U_C_Poloshirt_stripped",{}},{"rhs_chicom_khk",{}},{},"S_Pakol","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};

    };

    class I_Spagistan_Militiaman_M79 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Grenade Launcher)";
        uniformClass = "U_C_Poloshirt_tricolour";
        linkedItems[] = {"rhs_belt_AK_GL","S_Pakol","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_belt_AK_GL","S_Pakol","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m79"};
        respawnWeapons[] = {"rhs_weap_m79"};

        magazines[] = {"rhs_mag_M441_HE","rhs_mag_M441_HE"};
        respawnMagazines[] = {"rhs_mag_M441_HE","rhs_mag_M441_HE"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m79","","","",{"rhs_mag_M441_HE",1},{},""},{},{},{"U_C_Poloshirt_tricolour",{}},{"rhs_belt_AK_GL",{{"rhs_mag_M441_HE",10,1}}},{},"S_Turban","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};

    };

        class I_Spagistan_Militiaman_M3A1 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (SMG)";
        uniformClass = "U_C_Poloshirt_salmon";
        linkedItems[] = {"rhs_belt_AK_GL","S_Pakol","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_belt_AK_GL","S_Pakol","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};

        magazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};
        respawnMagazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m3a1","","","",{"rhsgref_30rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_C_Poloshirt_salmon",{}},{"rhs_6b2",{{"rhsgref_30rnd_1143x23_M1911B_SMG",1,30}}},{},"H_Cap_red","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};

    };
};
