//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CBA_Extended_EventHandlers_base;
class EventHandlers;
class I_G_Soldier_base_F;
class S_Tubitak_Spag;
class rhs_medic_bag;

class CfgVehicles {

    class S_Tubitak_Militia_AT : S_Tubitak_Spag {
        scope = 1;
        scopeArsenal = 1;
		class TransportMagazines
		{
			mag_xx(rhs_rpg7_PG7VL_mag,4);
			mag_xx(rhs_rpg7_OG7V_mag,2);
		};

    };

    class S_Medic_Bag_Militia : rhs_medic_bag {
        scope = 1;
        scopeArsenal = 1;
		class TransportItems
		{
			item_xx(ACE_salineIV,5);
			item_xx(ACE_surgicalKit,1);
            item_xx(ACE_suture,30);
            item_xx(ACE_tourniquet,4);
            item_xx(ACE_morphine,3);
            item_xx(ACE_epinephrine,3);
            item_xx(ACE_elasticBandage,20);
            item_xx(ACE_splint,3);
		};
    };

    class I_Spagistan_Militiaman_Base : I_G_Soldier_base_F {
        author = "A. Dan";
        scope = 0;
        scopeCurator = 0;
        side = 2;
        genericNames = "SpagistanMen";
        faction = "I_SPAG_Militia";
        editorCategory = "Spagistani_Militia_Category";
        identityTypes[] = {"Head_TK","LanguagePER_F"};
        linkedItems[] = {"cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {};
        respawnWeapons[] = {};
        magazines[] = {};
        respawnMagazines[] = {};
        Items[] = { "cigs_matches", "ACE_tourniquet" };
		RespawnItems[] = { "cigs_matches", "ACE_tourniquet" };
        headgearList[] =
		{
			"H_FakeHeadgear", 0.7,
			"S_Pakol", 0.5,
            "S_Turban", 0.5,
            "rhs_pilotka", 0.5,
            "rhs_fieldcap_m88_back", 0.5,
            "rhs_fieldcap_m88_", 0.2,
            "S_beret_green_NONE", 0.2,
            "H_Cap_blk", 0.2,
            "H_Cap_red", 0.2,
            "H_Hat_Safari_sand_F", 0.2

		};

		class EventHandlers : EventHandlers
		{
			init = "if (local (_this select 0)) then { [(_this select 0), [], []] call BIS_fnc_unitHeadgear; };";
        };
    };

        class I_Spagistan_Militiawoman_Base : I_Spagistan_Militiaman_Base {
        genericNames = "SpagistanWomen";
        identityTypes[] = {"Head_TK_W","LanguagePER_F"};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then { (_this select 0) spawn { sleep 0.3; (_this) setSpeaker 'rhs_female01ENG';}; [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class I_Spagistan_Militiaman_Izh18 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Shotgun)";
        uniformClass = "U_I_C_Soldier_Bandit_4_F";
        linkedItems[] = {"rhs_suspender_AK","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnLinkedItems[] = {"rhs_suspender_AK","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_Izh18"};
        respawnWeapons[] = {"rhs_weap_Izh18"};
        magazines[] = { ITEM_8("rhsgref_1Rnd_Slug"), ITEM_11("rhsgref_1Rnd_00Buck") };
        respawnMagazines[] = { ITEM_8("rhsgref_1Rnd_Slug"), ITEM_11("rhsgref_1Rnd_00Buck") };
    };

    class I_Spagistan_Militiaman_PM_63 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Rifle 1)";
        uniformClass = "U_I_C_Soldier_Bandit_1_F";
        linkedItems[] = {"rhs_gear_OFF","S_beret_green_NONE","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_gear_OFF","S_beret_green_NONE","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_pm63"};
        respawnWeapons[] = {"rhs_weap_pm63"};
        magazines[] = {ITEM_3("rhs_30Rnd_762x39mm"),};
        respawnMagazines[] = {ITEM_3("rhs_30Rnd_762x39mm"),};
    };

    class I_Spagistan_Militiaman_M84 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (GPMG)";
        uniformClass = "U_C_Poloshirt_stripped";
        linkedItems[] = {"rhs_chicom_khk","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_chicom_khk","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_m84"};
        respawnWeapons[] = {"rhs_weap_m84"};
        magazines[] = {"rhs_100Rnd_762x54mmR_7N13","rhs_100Rnd_762x54mmR_7N13"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR_7N13","rhs_100Rnd_762x54mmR_7N13"};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_stripped';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class I_Spagistan_Militiaman_M79 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (GL)";
        uniformClass = "U_C_Poloshirt_tricolour";
        linkedItems[] = {"rhs_belt_AK_GL","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_belt_AK_GL","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_m79"};
        respawnWeapons[] = {"rhs_weap_m79"};
        magazines[] = {ITEM_11("rhs_mag_M441_HE")};
        respawnMagazines[] = {ITEM_11("rhs_mag_M441_HE")};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_tricolour';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

        class I_Spagistan_Militiaman_M3A1 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (SMG)";
        uniformClass = "U_C_Poloshirt_salmon";
        linkedItems[] = {"rhs_belt_AK_GL","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_belt_AK_GL","S_Pakol","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};
        magazines[] = {ITEM_4("rhsgref_30rnd_1143x23_M1911B_SMG")};
        respawnMagazines[] = {ITEM_4("rhsgref_30rnd_1143x23_M1911B_SMG")};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_salmon';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class I_Spagistan_Militiaman_K98 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Rifle 2)";
        uniformClass = "U_I_C_Soldier_Para_5_F";
        linkedItems[] = {"cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_kar98k"};
        respawnWeapons[] = {"rhs_weap_kar98k"};
        magazines[] = {ITEM_10("rhsgref_5Rnd_792x57_kar98k"),};
        respawnMagazines[] = {ITEM_10("rhsgref_5Rnd_792x57_kar98k"),};
    };

    class I_Spagistan_Militiaman_RPG7 : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Anti-Tank)";
        uniformClass = "U_I_C_Soldier_Bandit_5_F";
        backpack = "S_Tubitak_Militia_AT";
        linkedItems[] = {"H_Hat_Safari_sand_F","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Hat_Safari_sand_F","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_rpg7"};
        respawnWeapons[] = {"rhs_weap_rpg7"};
        magazines[] = {ITEM_4("rhs_rpg7_PG7VL_mag"), ITEM_2("rhs_rpg7_OG7V_mag")};
        respawnMagazines[] = {ITEM_4("rhs_rpg7_PG7VL_mag"), ITEM_2("rhs_rpg7_OG7V_mag")};
    };

    class I_Spagistan_Militiaman_Mosin : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Rifle 3)";
        uniformClass = "U_I_C_Soldier_Bandit_3_F";
        linkedItems[] = {"rhs_chicom_khk","rhs_pilotka","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_chicom_khk","rhs_pilotka","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_m38"};
        respawnWeapons[] = {"rhs_weap_m38"};
        magazines[] = {ITEM_11("rhsgref_5Rnd_762x54_m38")};
        respawnMagazines[] = {ITEM_11("rhsgref_5Rnd_762x54_m38")};
    };

    class I_Spagistan_Militiawoman_M590A1 : I_Spagistan_Militiawoman_Base {
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiawoman (Shotgun)";
        uniformClass = "U_BG_Guerilla3_1";
        linkedItems[] = {"rhs_fieldcap_m88_back","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_fieldcap_m88_back","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_M590_8RD"};
        respawnWeapons[] = {"rhs_weap_M590_8RD"};
        magazines[] = {ITEM_5("rhsusf_8Rnd_Slug")};
        respawnMagazines[] = {ITEM_5("rhsusf_8Rnd_Slug")};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {
        (_this select 0) forceAddUniform 'U_BG_Guerilla3_1';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addMagazines ['rhsusf_8Rnd_Slug', 4];
        (_this select 0) spawn { sleep 0.3; (_this) setSpeaker 'rhs_female01ENG';};
         [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };
    class I_Spagistan_Militiawoman_Medic : I_Spagistan_Militiawoman_Base {
        scope = 2;
        scopeCurator = 2;
        attendant = 1;
        displayName = "Militiawoman (Medic)";
        uniformClass = "U_C_HunterBody_grn";
        backpack = "S_Medic_Bag_Militia";
        linkedItems[] = {"H_Bandanna_sand","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Bandanna_sand","cigs_morley_cig0","ItemMap","ItemCompass","ItemWatch"};
        weapons[] = {"rhs_weap_pp2000"};
        respawnWeapons[] = {"rhs_weap_pp2000"};
        magazines[] = {ITEM_3("rhs_mag_9x19mm_7n21_20")};
        respawnMagazines[] = {ITEM_3("rhs_mag_9x19mm_7n21_20")};
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {
            (_this select 0) forceAddUniform 'U_C_HunterBody_grn';
            (_this select 0) addItem 'ACE_tourniquet';
            (_this select 0) addMagazines ['rhs_mag_9x19mm_7n21_20', 3];
            (_this select 0) spawn {
                sleep 0.3;
                (_this) setSpeaker 'rhs_female01ENG';
                };
            [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class I_Spagistan_Yussy : I_Spagistan_Militiaman_Base {
        scope = 2;
        scopeCurator = 2;
        faction = "SPAG_F";
        editorCategory = "Spagistan_Category";
        displayName = "LTCOL, Y-Bn";
        genericNames = "YussyName";
        uniformClass = "U_I_C_Soldier_Para_3_F";
        linkedItems[] = {"U_I_C_Soldier_Para_3_F","rhs_6b13_6sh92_headset_mapcase","cigs_apollo_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"U_I_C_Soldier_Para_3_F","rhs_6b13_6sh92_headset_mapcase","cigs_apollo_cig0","ItemMap","ItemCompass","ItemWatch"};
        Items[] = { "cigs_lighter", "cigs_apollo_cigpack","ACE_painkillers", ITEM_2("ACE_tourniquet"), ITEM_3("ACE_quikclot"), "ACE_splint" };
		RespawnItems[] = { "cigs_lighter", "cigs_apollo_cigpack","ACE_painkillers", ITEM_2("ACE_tourniquet"), ITEM_3("ACE_quikclot"), "ACE_splint" };
        class EventHandlers : EventHandlers {
            init = "if (local (_this select 0)) then {
                (_this select 0) forceAddUniform 'U_I_C_Soldier_Para_3_F';
                (_this select 0) addItem 'cigs_lighter';
                (_this select 0) addItem 'cigs_apollo_cigpack';
                (_this select 0) addItem 'ACE_painkillers';
                (_this select 0) addItem 'ACE_tourniquet';
                (_this select 0) addItem 'ACE_tourniquet';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_splint';

                (_this select 0) spawn {
                    params ['_unit'];
                    sleep 0.3;
                    _unit setSpeaker 'Male01RUS';
                    _unit setFace 'Instructor';
                };
            };";
        };
    };

    class I_Spagistan_Yussy_Beach : I_Spagistan_Yussy {
        displayName = "LTCOL, Y-Bn (Beach)";
        uniformClass = "U_C_man_sport_2_F";
        linkedItems[] = {"U_C_man_sport_2_F","rhs_6sh92_headset","cigs_apollo_cig0","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"U_C_man_sport_2_F","rhs_6sh92_headset","cigs_apollo_cig0","ItemMap","ItemCompass","ItemWatch"};
        class EventHandlers : EventHandlers {
            init = "if (local (_this select 0)) then {
                (_this select 0) forceAddUniform 'U_C_man_sport_2_F';
                (_this select 0) addItem 'cigs_lighter';
                (_this select 0) addItem 'cigs_apollo_cigpack';
                (_this select 0) addItem 'ACE_painkillers';
                (_this select 0) addItem 'ACE_tourniquet';
                (_this select 0) addItem 'ACE_tourniquet';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_quikclot';
                (_this select 0) addItem 'ACE_splint';
                (_this select 0) spawn {
                    params ['_unit'];
                    sleep 0.3;
                    _unit setSpeaker 'Male01RUS';
                    _unit setFace 'Instructor';

                };
            };";
        };
    };

///// _____OPFOR MILITIA_____ /////
    class O_Spagistan_Militiaman_Izh18_opfor : I_Spagistan_Militiaman_Izh18 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_C_Soldier_Bandit_4_F';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_PM_63_opfor : I_Spagistan_Militiaman_PM_63 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_C_Soldier_Bandit_1_F';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_M84_opfor : I_Spagistan_Militiaman_M84 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_stripped';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_M79_opfor : I_Spagistan_Militiaman_M79 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_tricolour';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_M3A1_opfor : I_Spagistan_Militiaman_M3A1 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_salmon';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_K98_opfor : I_Spagistan_Militiaman_K98 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_C_Soldier_Para_5_F';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_RPG7_opfor : I_Spagistan_Militiaman_RPG7 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_C_Soldier_Bandit_5_F';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiaman_Mosin_opfor : I_Spagistan_Militiaman_Mosin {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_C_Soldier_Bandit_3_F';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class O_Spagistan_Militiawoman_M590A1_opfor : I_Spagistan_Militiawoman_M590A1 {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then { (_this select 0) spawn { sleep 0.3; (_this) setSpeaker 'rhs_female01ENG';};
        (_this select 0) forceAddUniform 'U_BG_Guerilla3_1'; [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };
    class O_Spagistan_Militiawoman_Medic_opfor : I_Spagistan_Militiawoman_Medic {
        side = 0;
        faction = "O_SPAG_Militia_OPFOR";
        editorCategory = "Spagistani_Militia_OPFOR_Category";
        class EventHandlers : EventHandlers
        {
        init = "if (local (_this select 0)) then { (_this select 0) spawn { sleep 0.3; (_this) setSpeaker 'rhs_female01ENG';};
        (_this select 0) forceAddUniform 'U_C_HunterBody_grn'; [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };
/////_____CIVILIANS_____/////

    class C_Spag_Civ_Base : I_Spagistan_Militiaman_Base {
        side = 3;
        faction = "C_SPAG_Civ";
        editorCategory = "Spagistani_Civilian_Category";
    };

    class C_Spag_Civ1 : I_Spagistan_Militiaman_RPG7 {
        SPAG_MILITA_TO_CIV_CONFIG
        displayName = "Civilian 1";
    };

    class C_Spag_Civ2 : I_Spagistan_Militiaman_K98 {
        SPAG_MILITA_TO_CIV_CONFIG
        displayName = "Civilian 2";
    };

        class C_Spag_Civ3 : I_Spagistan_Militiaman_PM_63 {
        SPAG_MILITA_TO_CIV_CONFIG
        displayName = "Civilian 3";
    };

    class C_Spag_Civ_Woman1 : I_Spagistan_Militiawoman_M590A1 {
        SPAG_MILITA_TO_CIV_CONFIG
        displayName = "Civilian, Woman 1";
    };

    class C_Spag_Civ_Woman2 : I_Spagistan_Militiawoman_Medic {
        SPAG_MILITA_TO_CIV_CONFIG
        displayName = "Civilian, Woman 2";
    };

    class C_Spag_Civ_Dealer1 : C_Spag_Civ_Base {
        displayName = "Dealer 1";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_C_FormalSuit_01_tshirt_gray_F";
        linkedItems[] = {"S_Turban","G_Aviator","ItemMap","ItemCompass","ItemWatch","cigs_cigars_cigar0_nv"};
        respawnLinkedItems[] = {"S_Turban","G_Aviator","ItemMap","ItemCompass","ItemWatch","cigs_cigars_cigar0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_FormalSuit_01_tshirt_gray_F';};";
        };
    };

    class C_Spag_Civ_Dealer2 : C_Spag_Civ_Dealer1 {
        displayName = "Dealer 2";
        uniformClass = "U_C_FormalSuit_01_tshirt_black_F";
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_FormalSuit_01_tshirt_black_F';};";
        };
    };

    class C_Spag_Civ_Trad1 : C_Spag_Civ_Base {
        displayName = "Civilian, Traditional (Beige)";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "S_Uniform_Civ1";
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'S_Uniform_Civ1';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class C_Spag_Civ_Trad2 : C_Spag_Civ_Base {
        displayName = "Civilian, Traditional (Violet)";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "S_Uniform_Civ2";
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'S_Uniform_Civ2';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class C_Spag_Civ_Trad3 : C_Spag_Civ_Base {
        displayName = "Civilian, Traditional (Blue)";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "S_Uniform_Civ3";
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'S_Uniform_Civ3';
        [(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
        };
    };

    class C_Spag_Civ_Const_Base : C_Spag_Civ_Base {
    Items[] = { "cigs_matches", "ACE_tourniquet", "ACE_fortify", "ACE_EntrenchingTool" };
	RespawnItems[] = { "cigs_matches", "ACE_tourniquet", "ACE_fortify", "ACE_EntrenchingTool" };
    };

    class C_Spag_Civ_Const1 : C_Spag_Civ_Const_Base {
        displayName = "Worker 1";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_C_Poloshirt_Salmon";
        linkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F", "G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        respawnLinkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F","G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_Salmon';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };

    class C_Spag_Civ_Const2 : C_Spag_Civ_Const_Base {
        displayName = "Worker 2";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_C_Poloshirt_tricolour";
        linkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F", "G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        respawnLinkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F","G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Poloshirt_tricolour';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };

    class C_Spag_Civ_Const3 : C_Spag_Civ_Const_Base {
        displayName = "Worker 3";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_BG_Guerilla2_2";
        linkedItems[] = {"H_Construction_earprot_yellow_F","V_safety_orange_F", "G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        respawnLinkedItems[] = {"H_Construction_earprot_yellow_F","V_safety_orange_F","G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_BG_Guerilla2_2';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };

    class C_Spag_Civ_Const4 : C_Spag_Civ_Const_Base {
        displayName = "Worker 4";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_I_L_Uniform_01_tshirt_olive_F";
        linkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F", "G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        respawnLinkedItems[] = {"H_Construction_basic_yellow_F","V_safety_orange_F","G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_I_L_Uniform_01_tshirt_olive_F';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };

    class C_Spag_Civ_Const5 : C_Spag_Civ_Const_Base {
        displayName = "Worker 5";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_C_Mechanic_01_F";
        linkedItems[] = {"H_Construction_basic_orange_F","V_safety_orange_F", "G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        respawnLinkedItems[] = {"H_Construction_basic_orange_F","V_safety_orange_F","G_Eyeprotectors_F","ItemMap","ItemCompass","ItemWatch","cigs_morley_cig0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_C_Mechanic_01_F';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };

    class C_Spag_Civ_Foreman : C_Spag_Civ_Const_Base {
        displayName = "Foreman";
        scope = 2;
        scopeCurator = 2;
        uniformClass = "U_Marshal";
        linkedItems[] = {"H_Construction_basic_white_F","V_safety_orange_F", "G_Aviator","ItemMap","ItemCompass","ItemWatch","cigs_cigars_cigar0_nv"};
        respawnLinkedItems[] = {"H_Construction_basic_white_F","V_safety_orange_F","G_Aviator","ItemMap","ItemCompass","ItemWatch","cigs_cigars_cigar0_nv"};
        class EventHandlers : EventHandlers {
        init = "if (local (_this select 0)) then {(_this select 0) forceAddUniform 'U_Marshal';
        (_this select 0) addItem 'ACE_tourniquet';
        (_this select 0) addItem 'ACE_fortify';
        (_this select 0) addItem 'ACE_EntrenchingTool';
        };";
        };
    };
};
