//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_Spagistan_NG {
        displayName = "Spagistan National Guard";
        side = 2;
        flag = "\z\spag\addons\common\gui\Spag_Flag_ca.paa";
        icon = "\z\spag\addons\common\gui\Spag_Flag_Square_ca.paa";
        priority = 6;
    };
};