class CfgPatches {
    class I_Spagistan_NG {
        units[] = {
            "NG_Soldier_Rifleman",
            "NG_Soldier_Grenadier",
            "NG_Soldier_AR",
            "NG_Soldier_TeamLeader",
            "I_Spagistan_NG_Squad_Lead_01",
            "I_Spagistan_NG_M113_01",
            "I_Spagistan_NG_Crewman_01",
            "I_Spagistan_NG_BTR_70_01",
            "I_Spagistan_NG_BMP_1_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "spag_Factions",
            "A3_Characters_F",
            "rhs_c_troops",
            "rhs_cti_insurgents",
            "rhsgref_c_troops",
            "rhssaf_c_troops",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "immersion_pops",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "ace_thermals",
            "zen_attributes",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh",
            "spag_vehicles",
            "rhsusf_c_m113",
            "ace_compat_rhs_usf3",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "ace_interaction",
            "ace_vehicle_damage",
            "ace_vehicles",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "rhs_c_2s1",
            "rhs_c_2s3",
            "rhs_c_bmd",
            "rhs_c_bmp3",
            "rhs_c_bmp",
            "rhs_c_pts",
            "rhs_c_sprut",
            "rhs_c_t14",
            "rhs_c_t15",
            "rhs_c_t72",
            "rhs_c_tanks",
            "RHS_US_A2Port_Armor",
            "rhsusf_c_m109",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhs_c_a2port_armor",
            "ace_cookoff",
            "ace_logistics_uavbattery",
            "rhssaf_c_vehicles",
            "rhsgref_c_vehicles_ret",
            "A3_Data_F_ParticleEffects",
            "ace_tagging",
            "ace_cargo",
            "I_Spagistan_Garmsar",
            "rhs_c_btr",
            "ace_compat_rhs_afrf3",
            "ace_compat_rhs_afrf3_repair",
            "TFAR_IntercomDummy",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "rhsgref_c_a2port_armor",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02"
        };
        author = "Canadian";
        authors[] = {"Canadian"};
    };
};

