//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152893 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class NG_Soldier_Base;
    class NG_Soldier_Base_OCimport_01 : NG_Soldier_Base { scope = 0; class EventHandlers; };
    class NG_Soldier_Base_OCimport_02 : NG_Soldier_Base_OCimport_01 { class EventHandlers; };

    class m113_spagpat;
    class m113_spagpat_OCimport_01 : m113_spagpat { scope = 0; class EventHandlers; class Turrets; };
    class m113_spagpat_OCimport_02 : m113_spagpat_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret_In;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class S_Soldier_Armor;
    class S_Soldier_Armor_OCimport_01 : S_Soldier_Armor { scope = 0; class EventHandlers; };
    class S_Soldier_Armor_OCimport_02 : S_Soldier_Armor_OCimport_01 { class EventHandlers; };

    class rhsgref_cdf_btr70;
    class rhsgref_cdf_btr70_OCimport_01 : rhsgref_cdf_btr70 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_btr70_OCimport_02 : rhsgref_cdf_btr70_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class BMP_Spagpat;
    class BMP_Spagpat_OCimport_01 : BMP_Spagpat { scope = 0; class EventHandlers; class Turrets; };
    class BMP_Spagpat_OCimport_02 : BMP_Spagpat_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class Com_BMP1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };


    class NG_Soldier_Rifleman : NG_Soldier_Base_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_Asian","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"S_weap_ak74m_ip78","rhs_weap_rpg75","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"S_weap_ak74m_ip78","rhs_weap_rpg75","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};

        backpack = "NG_KitBag_RF";

        ALiVE_orbatCreator_loadout[] = {{"S_weap_ak74m_ip78","rhs_acc_dtk","","rhs_acc_1p78",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{"rhs_weap_rpg75","","","",{},{},""},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_30Rnd_545x39_7N10_AK",5,30}}},{"rhssaf_vest_md12_digital",{{"rhs_30Rnd_545x39_7N10_AK",4,30}}},{"NG_KitBag_RF",{{"ACE_elasticBandage",30},{"ACE_packingBandage",10},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"rhssaf_helmet_m97_olive_nocamo","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class NG_Soldier_Grenadier : NG_Soldier_Base_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"S_weap_ak74m_gp25_ip78","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"S_weap_ak74m_gp25_ip78","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_VOG25","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_VOG25","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_VOG25","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_VOG25","rhs_mag_9x18_8_57N181S"};

        backpack = "NG_KitBag_GR";

        ALiVE_orbatCreator_loadout[] = {{"S_weap_ak74m_gp25_ip78","rhs_acc_dtk","","rhs_acc_1p78",{"rhs_30Rnd_545x39_7N10_AK",30},{"rhs_VOG25",1},""},{},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_30Rnd_545x39_7N10_AK",5,30}}},{"rhssaf_vest_md12_digital",{{"rhs_30Rnd_545x39_7N10_AK",4,30}}},{"NG_KitBag_GR",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"rhs_VOG25",9,1},{"rhs_VOG25P",5,1},{"rhs_VG40MD",5,1},{"rhs_GRD40_White",5,1},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"rhssaf_helmet_m97_olive_nocamo","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class NG_Soldier_AR : NG_Soldier_Base_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Automatic Rifleman";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"S_weap_rpk_ip78","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"S_weap_rpk_ip78","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_60Rnd_545X39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_60Rnd_545X39_7N10_AK","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_60Rnd_545X39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_60Rnd_545X39_7N10_AK","rhs_mag_9x18_8_57N181S"};

        backpack = "NG_KitBag_AR";

        ALiVE_orbatCreator_loadout[] = {{"S_weap_rpk_ip78","rhs_acc_dtk","","rhs_acc_1p78",{"rhs_60Rnd_545X39_7N10_AK",60},{},""},{},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_60Rnd_545X39_7N10_AK",2,60}}},{"rhssaf_vest_md12_digital",{{"rhs_60Rnd_545X39_7N10_AK",5,60}}},{"NG_KitBag_AR",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_morphine",3},{"ACE_epinephrine",3},{"ACE_splint",3},{"ACE_tourniquet",4},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"rhs_60Rnd_545X39_7N10_AK",5,60},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"rhssaf_helmet_m97_olive_nocamo","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class NG_Soldier_TeamLeader : NG_Soldier_Base_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhssaf_vest_md12_digital","rhssaf_helmet_m97_olive_nocamo","ItemMap","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"S_weap_ak74m_ip78","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"S_weap_ak74m_ip78","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};

        backpack = "NG_KitBag_TL";

        ALiVE_orbatCreator_loadout[] = {{"S_weap_ak74m_ip78","rhs_acc_dtk","","rhs_acc_1p78",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_30Rnd_545x39_7N10_AK",5,30}}},{"rhssaf_vest_md12_digital",{{"rhs_30Rnd_545x39_7N10_AK",4,30}}},{"NG_KitBag_TL",{{"ACE_elasticBandage",15},{"ACE_packingBandage",10},{"ACE_morphine",6},{"ACE_epinephrine",6},{"ACE_splint",5},{"ACE_tourniquet",8},{"ACE_suture",40},{"ACE_salineIV_250",5},{"ACE_salineIV_500",5},{"ACE_salineIV",3},{"ACE_surgicalKit",1},{"ACE_Sandbag_empty",3},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"rhssaf_helmet_m97_olive_nocamo","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class I_Spagistan_NG_Squad_Lead_01 : NG_Soldier_TeamLeader {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"rhssaf_vest_md12_digital","S_beret_green_SPAGPAT","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhssaf_vest_md12_digital","S_beret_green_SPAGPAT","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"S_weap_ak74m_ip78","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"S_weap_ak74m_ip78","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x18_8_57N181S"};

        backpack = "NG_KitBag_TL";

        ALiVE_orbatCreator_loadout[] = {{"S_weap_ak74m_ip78","rhs_acc_dtk","","rhs_acc_1p78",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_30Rnd_545x39_7N10_AK",5,30}}},{"rhssaf_vest_md12_digital",{{"rhs_30Rnd_545x39_7N10_AK",4,30}}},{"NG_KitBag_TL",{{"ACE_elasticBandage",15},{"ACE_packingBandage",10},{"ACE_morphine",6},{"ACE_epinephrine",6},{"ACE_splint",5},{"ACE_tourniquet",8},{"ACE_suture",40},{"ACE_salineIV_250",5},{"ACE_salineIV_500",5},{"ACE_salineIV",3},{"ACE_surgicalKit",1},{"ACE_Sandbag_empty",3},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"S_beret_green_SPAGPAT","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class I_Spagistan_NG_M113_01 : m113_spagpat_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "M113";
        side = 2;
        faction = "i_spagistan_ng";
        crew = "I_Spagistan_NG_Crewman_01";

        class Turrets : Turrets {
            class MainTurret_In : MainTurret_In { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Spagistan_NG_Crewman_01 : S_Soldier_Armor_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 2;
        faction = "i_spagistan_ng";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_S_Uniform_SPAGPAT";

        linkedItems[] = {"S_Vest_SPAGPAT","rhs_tsh4_bala","ItemMap","TFAR_anprc148jem","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"S_Vest_SPAGPAT","rhs_tsh4_bala","ItemMap","TFAR_anprc148jem","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u","rhs_weap_makarov_pm"};
        respawnWeapons[] = {"rhs_weap_aks74u","rhs_weap_makarov_pm"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x18_8_57N181S"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x18_8_57N181S","rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x18_8_57N181S"};

        backpack = "S_KitBag_Spag_Rifleman";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_dtk","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{"rhs_weap_makarov_pm","","","",{"rhs_mag_9x18_8_57N181S",8},{},""},{"U_S_Uniform_SPAGPAT",{{"ACE_microDAGR",1},{"ACE_CableTie",2},{"ACE_EarPlugs",2},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"S_Vest_SPAGPAT",{}},{"S_KitBag_Spag_Rifleman",{{"ACE_elasticBandage",30},{"ACE_morphine",4},{"ACE_epinephrine",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_EntrenchingTool",1},{"rhssaf_mag_br_m75",5,1},{"rhssaf_mag_brd_m83_white",5,1},{"acex_intelitems_notepad",1,1},{"murshun_cigs_cigpack",1,20},{"murshun_cigs_lighter",1,100}}},"rhs_tsh4_bala","G_Shades_Black",{},{"ItemMap","","TFAR_anprc148jem","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spagistan_Insignia'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spagistan_Insignia";

    };

    class I_Spagistan_NG_BTR_70_01 : rhsgref_cdf_btr70_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR-70";
        side = 2;
        faction = "i_spagistan_ng";
        crew = "I_Spagistan_NG_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Spagistan_NG_Crewman_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "I_Spagistan_NG_Crewman_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsgref\addons\rhsgref_vehicles_ret\data\misc\btr70_tak_1_co.paa'];_unit setObjectTextureGlobal [1,'rhsgref\addons\rhsgref_vehicles_ret\data\misc\btr70_tak_2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Takistan";

    };

    class I_Spagistan_NG_BMP_1_01 : BMP_Spagpat_OCimport_02 {
        author = "Canadian";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMP-1";
        side = 2;
        faction = "i_spagistan_ng";
        crew = "I_Spagistan_NG_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Spagistan_NG_Crewman_01"; };
            class Com_BMP1 : Com_BMP1 { gunnerType = "I_Spagistan_NG_Crewman_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp_camo\data\bmp_1_desert_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp_camo\data\bmp_2_desert_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp_camo\data\bmp_3_desert_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp_camo\data\bmp_4_desert_co.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\rhs_bmp_camo\data\bmp_5_desert_co.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\rhs_bmp_camo\data\bmp_6_desert_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "rhs_sand";

    };

};