name: Build and Release

on:
  pull_request:
    branches:
      - "master"
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get all history for changelog

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT build (release mode)
        run: hemtt release

      - name: Rename build folder
        run: mv .hemttout/release .hemttout/@safe

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safe
          path: .hemttout/@safe
          if-no-files-found: error

  release:
    name: Release
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: safe
          path: artifacts/safe

      - name: Zip mod
        run: |
          ls
          mv artifacts/safe artifacts/@safe
          zip -r artifacts/@safe.zip artifacts/@safe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/@safe.zip
          name: ${{ needs.build.outputs.VERSION }}

      - name: Upload to Steam Workshop
        uses: arma-actions/workshop-upload@v1
        with:
          appId: "107410"
          itemId: "3615632492" # Dev Builds (change if needed)
          contentPath: "artifacts/@safe"
          changelog: "Version ${{ needs.build.outputs.VERSION }}"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
