name: Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:



jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release
        - name: Rename build folder
          run: mv .hemttout/release .hemttout/@spag
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: safe-${{ github.sha }}
            path: .hemttout/@*
            include-hidden-files: true # Because .hemttout is a hidden directory 