name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release
        - name: Rename build folder
          run: mv .hemttout/release .hemttout/@spag
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: safe-${{ github.ref_name }}
            path: .hemttout/@*
            include-hidden-files: true # Because .hemttout is a hidden directory 
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            release_name: Release ${{ github.ref_name }}
            body: |
              **[Changelog](https://github.com/Kalthramis/Spagistan/compare/v${{ github.ref_name }}...v${{ github.ref_name }})**